openapi: 3.0.3
info:
  title: Swagger X(Twitter) clone - OpenAPI 3.0
  description: |-
    This is a X(Twitter) clone Server based on the OpenAPI 3.0 specification
  contact:
    email: hoangsangho93@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:4000/

paths:
  /users/login:
    $ref: './paths/user.paths.yaml#/paths/~1users~1login'
  /users/me:
    $ref: './paths/user.paths.yaml#/paths/~1users~1me'
